queue:
  name: Hosted VS2017
  demands: npm


steps:
- task: Npm@1
  inputs:
    verbose: false

- task: Npm@1
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'

- task: Npm@1
  inputs:
    verbose: false

- task: CmdLine@1
  inputs:
    filename: 'firebase deploy --token $(FIREBASE_TOKEN)'

